-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 22:16:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pagekeeperweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pagekeeperweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pagekeeperweb` DEFAULT CHARACTER SET utf8mb4 ;
USE `pagekeeperweb` ;

-- -----------------------------------------------------
-- Table `pagekeeperweb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`autores` (
  `idAutor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreAutor` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`generos` (
  `idGenero` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreGenero` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`libros` (
  `idLibro` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreLibro` TEXT NOT NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`librosautores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`librosautores` (
  `idLibrosAutores` INT(11) NOT NULL AUTO_INCREMENT,
  `idAutor` INT(11) NULL DEFAULT NULL,
  `idLibro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idLibrosAutores`),
  INDEX `idAutor` (`idAutor` ASC) VISIBLE,
  INDEX `idLibro` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `librosautores_ibfk_1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `pagekeeperweb`.`autores` (`idAutor`),
  CONSTRAINT `librosautores_ibfk_2`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`),
  CONSTRAINT `librosautores_ibfk_3`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`librosgenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`librosgenero` (
  `idLibrosGenero` INT(11) NOT NULL AUTO_INCREMENT,
  `idGenero` INT(11) NULL DEFAULT NULL,
  `idLibro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idLibrosGenero`),
  INDEX `idGenero` (`idGenero` ASC) VISIBLE,
  INDEX `idLibro` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `librosgenero_ibfk_1`
    FOREIGN KEY (`idGenero`)
    REFERENCES `pagekeeperweb`.`generos` (`idGenero`),
  CONSTRAINT `librosgenero_ibfk_2`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`),
  CONSTRAINT `librosgenero_ibfk_3`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`ventas` (
  `idVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `pagekeeperweb`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`librosventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`librosventas` (
  `idLibrosVentas` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL,
  `valorVenta` DOUBLE NOT NULL,
  `idVenta` INT(11) NULL DEFAULT NULL,
  `idLibro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idLibrosVentas`),
  INDEX `idVenta` (`idVenta` ASC) VISIBLE,
  INDEX `idLibro` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `librosventas_ibfk_1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `pagekeeperweb`.`ventas` (`idVenta`),
  CONSTRAINT `librosventas_ibfk_2`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pagekeeperweb`.`usuarioslibros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagekeeperweb`.`usuarioslibros` (
  `idUsuariosLibros` INT(11) NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NOT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  `idLibro` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuariosLibros`),
  INDEX `usuarioslibros_ibfk_1` (`idUsuario` ASC) VISIBLE,
  INDEX `usuarioslibros_ibfk_3` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `usuarioslibros_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `pagekeeperweb`.`usuarios` (`idUsuario`)
    ON UPDATE CASCADE,
  CONSTRAINT `usuarioslibros_ibfk_2`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`)
    ON UPDATE CASCADE,
  CONSTRAINT `usuarioslibros_ibfk_3`
    FOREIGN KEY (`idLibro`)
    REFERENCES `pagekeeperweb`.`libros` (`idLibro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
